### ISSUE TITLE
Where can I get dailyInterestRate?

### ISSUE THREAD

**Issue by phuongphally** [Vovke/loan-payments-calculator#4]
How to calculate it? 

$dailyInterestRate = 0.000383;

**Comment by Vovke** [comment]
Hey, in order to calculate dailyInterestRate, you can do following, assuming your annual rate is 10%
1. Convert the percentage rate to a decimal: 10 ÷ 100 = 0.10
2. Convert the annual rate to a daily rate: 0.10 ÷ 365 = 0.00027397
hope that helps

**Comment by phuongphally** [comment]
@Vovke  Thank you.
